sudo: false
language: rust
notifications:
  webhooks: http://build.servo.org:54856/travis

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

script:
  - cargo build
  # https://github.com/servo/gaol/issues/18
  - cargo test --no-run
