sudo: false
language: rust
rust: nightly
notifications:
  webhooks: http://build.servo.org:54856/travis

os:
  - linux
  - osx

script:
  - cargo build
  # https://github.com/servo/gaol/issues/18
  - cargo test --no-run
